### PR TITLE
Enhance markdown docs

### LINKED ISSUE #99: Enhance markdown docs
Next steps for jsdoc-to-markdown configuration:

https://github.com/OpenFn/adaptors/blob/main/tools/build/src/commands/docs.ts#L12-L16

- [x]  Include the readme
- [ ]  ~Customise the template so it's prettier for docusaurus~

This will then be called by #22 and used by docs.openfn.org in docusarus.

### PR DESCRIPTION
**Pull request by mtuchi**
### Related Issue
Fixes #99

### CODE REVIEW

**Comment by mtuchi** [comment]
@taylordowns2000 how do i  `Customise the template so it's prettier for docusaurus` ?

**Comment by mtuchi** [comment]
@taylordowns2000
You can review and merge now, This is the link to [How to create a template](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-README-template)

**Comment by mtuchi** [comment]
Here is the list of examples we can use for future styling 🖌️ 🎨 
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Exemplary-APIs

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
hi @mtuchi , this looks like _more_ has changed than the stuff in #99 . is a rebase needed? (i think we should probably be reviewing one or two files here but this one shows 40.)

**Comment by mtuchi** [comment]
> hi @mtuchi , this looks like _more_ has changed than the stuff in #99 . is a rebase needed? (i think we should probably be reviewing one or two files here but this one shows 40.)

@taylordowns2000 I reverted the rebase, should be good to review now

**Pull request merged**
