### PR TITLE
Commcare: update documentation

### LINKED ISSUE #775: commcare: update docs and add examples
For HIH/Asri we've been using the CommCare adaptor in cool ways - let's document some of these learnings and examples! 
- Please review the docs we have on existing [functions](https://docs.openfn.org/adaptors/packages/commcare-docs) to see if anything needs updating. Also pls make sure all options are documented. 
- Do you have any examples from this Asri project you can add [as new Examples](https://docs.openfn.org/adaptors/library/jobs/auto/Registration-forms-new-case-2023-06-22)? It would be great to see some examples for getting cases, getting and updating lookup tables, etc. 
- The [configuration](https://docs.openfn.org/adaptors/packages/commcare-configuration-schema) does not look up-to-date and is maybe missing UN and password. Can you please review this?

### PR DESCRIPTION
**Pull request by hunterachieng**
## Summary

Update `commcare` documentation with more examples and better formatting

Fixes #775 

## Details

Add more examples and update the `commcare` documentation

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Review Checklist

Before merging, the reviewer should check the following items:

- [ ] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, added the adaptor on marketing website ?
- [ ] Are there any unit tests?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.
- [ ] Have you ticked a box under AI Usage?

### CODE REVIEW

**Review by josephjclark — CHANGES_REQUESTED** [review]
Just a bit of pasted code that needs removing please

**Review by josephjclark — APPROVED** [review]
Looks good

Aleksa said something about configuration in the issue - is that anything that needs addressing here?

**Comment by hunterachieng** [comment]
> Looks good
> 
> Aleksa said something about configuration in the issue - is that anything that needs addressing here?

Not really, the configuration docs is accurate and up to date

**Comment by josephjclark** [comment]
@hunterachieng what about the [Sample Configuration](https://docs.openfn.org/adaptors/packages/commcare-configuration-schema#sample-configuration)? Should that have a user/pass or apikey? Just as a starting point for users. Maybe an app id too?

**Comment by josephjclark** [comment]
@hunterachieng Oh I see, the sample configuration comes from required keys. hmm.

We  can't make username and password required, because they're not required if you pass an API key. So we'll have to live without those in the example.

I presume appId is always required though? 

What about hostURL? Is that really required or can we (do we?) safely default that to commcarehq?

**Comment by hunterachieng** [comment]
> @hunterachieng Oh I see, the sample configuration comes from required keys. hmm.
> 
> We can't make username and password required, because they're not required if you pass an API key. So we'll have to live without those in the example.
> 
> I presume appId is always required though?
> 
> What about hostURL? Is that really required or can we (do we?) safely default that to commcarehq?

@josephjclark  hostURL is a required field

**Comment by josephjclark** [comment]
Ok @hunterachieng , thank you! I'll get this merged in a minute

**Pull request merged**
