### PR TITLE
integration tests

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Add integration tests. These tests are using nodejs http and https modules for creating a server that is used in tests. 
The http server is used for testing redirects, while the https server is used for testing the `tls` support. 
In addition the https server is also using koa and koa-sslify packages.

You will notice a `test/helpers/` directory which contain `certs.js`. These are the certificates that we are using for the https server for testing 

Ref #402 #406 

## Review Checklist

Before merging, the reviewer should check the following items:

- [x] Does the PR do what it claims to do?
- [x] Are there any unit tests? Should there be?
- [ ] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

### CODE REVIEW

**Review by josephjclark — CHANGES_REQUESTED** [review]
I'm afraid I'm seeing a number of high-level issues here, I'm not quite sure what's happened.

The `test/intergration.js` file needs renaming to `test/integration.js` (there's only one R in integration). This is on the base branch and affects many of our branches, but let's get it sorted out here and merge it down.

I didn't think you wanted to use the koa server, but at the moment the tests seem to rely on it? Also at the moment we're declaring one set of servers in `intergration.js`, but also importing a different set of servers in `test/helpers/server.js`. So I'm a little confused about the intention. This is the sort of thing where a little comment in the PR description can help dispel confusion and make reviewing a little easier.

There is too much logging in the test code. Logging is useful while writing tests but it's really annoying in CI or when doing other work because the test output is spammed with meaningless stuff. So I'd really like to tighten up the use of logging here.

Also, all integration tests are failing locally. CI is failing too.

**Comment by mtuchi** [comment]
@josephjclark I don't know why the CI is failing because locally all test are passing

**Comment by mtuchi** [comment]
It turns out in ubuntu any `port < 1024` needs root permission, So i have updated the `httpsPort` to `1443` cc @josephjclark

**Comment by josephjclark** [comment]
@mtuchi Great catch on the port number, I had no idea!

What about koa and http - do we need both server implementations?

**Comment by mtuchi** [comment]
> What about koa and http - do we need both server implementations?

Hiya @josephjclark i have removed the koa implementation, and use the nodejs https module

**Review by josephjclark — APPROVED** [review]
Merci!

**Pull request merged**
