### PR TITLE
83 migrate common

### PR DESCRIPTION
**Pull request by taylordowns2000**
@josephjclark (cc @mtuchi) - there are two things we're bumping into here as we try to finish #83 :

## 1 - We can't build common when it includes the full module import/export statements on line 6-8 of [Adaptor.js](https://github.com/OpenFn/adaptors/blob/b31e9f59109617183c7ea7f0a2773aa0892e8b85/packages/common/src/Adaptor.js)
```js
export * as beta from './beta';
export * as http from './http';
export * as dateFns from './dateFns';
```
We get a complaint about deoptimizePath:
```
CLI Building entry: /Users/taylor/adaptors/packages/common/src/index.js
│ CLI tsup v6.3.0
│ DTS Build start
│ TypeError: Cannot read properties of null (reading 'deoptimizePath')
│     at Module.includeAllExports (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12780:26)
│     at Object.includeAllExports (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12869:43)
│     at NamespaceVariable.include (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12151:22)
│     at Module.includeVariable (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:13189:22)
│     at Module.includeAllExports (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12791:26)
│     at Object.includeAllExports (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12869:43)
│     at NamespaceVariable.include (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12151:22)
│     at Module.includeVariable (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:13189:22)
│     at Module.includeAllExports (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:12782:26)
│     at Graph.includeStatements (/Users/taylor/adaptors/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:23159:36)
│ /Users/taylor/adaptors/node_modules/.pnpm/tsup@6.3.0_mwhvu7sfp6vq5ryuwb6hlbjfka/node_modules/tsup/dist/index.js:2181
│                   reject(new Error("error occured in dts build"));
│                          ^
│ Error: error occured in dts build
│     at Worker.<anonymous> (/Users/taylor/adaptors/node_modules/.pnpm/tsup@6.3.0_mwhvu7sfp6vq5ryuwb6hlbjfka/node_modules/tsup/dist/index.js:2181:26)
│     at Worker.emit (node:events:513:28)
│     at MessagePort.<anonymous> (node:internal/worker:233:53)
│     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
│     at exports.emitMessage (node:internal/per_context/messageport:23:28)
│ Node.js v18.10.0
```

## 2 - Have we lost the ability to import `@openfn/language-common` in the ES style?

If so, we'll need to change the way all these adaptors import common, which doesn't seem ideal.

```js
│ file:///Users/taylor/adaptors/packages/asana/src/Adaptor.js:3
│   execute as commonExecute,
│   ^^^^^^^
│ SyntaxError: Named export 'execute' not found. The requested module '@openfn/language-common' is a Common
│ CommonJS modules can always be imported via the default export, for example using:
│ import pkg from '@openfn/language-common';
│     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
│     at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
│     at async Promise.all (index 0)
│     at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
│     at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
│     at async exports.loadFilesAsync (/Users/taylor/adaptors/node_modules/.pnpm/mocha@7.2.0/node_modules/m
│     at async singleRun (/Users/taylor/adaptors/node_modules/.pnpm/mocha@7.2.0/node_modules/mocha/lib/cli/
│     at async exports.runMocha (/Users/taylor/adaptors/node_modules/.pnpm/mocha@7.2.0/node_modules/mocha/l
│     at async exports.handler (/Users/taylor/adaptors/node_modules/.pnpm/mocha@7.2.0/node_modules/mocha/li
```

### CODE REVIEW

**Comment by josephjclark** [comment]
It turns out (2) is a problem with how we're declaring exports from the index.js file. I've fixed that here in #95 and will apply it more widely in a separate branch. There is actually a note in the readme about how to resolve this, but I've had time this afternoon to work out a better solution (and so simplify the instructions)

**Comment by josephjclark** [comment]
The first issue (as discussed on the call with Stu earlier) is caused by axios in the `.dts` (type definition) part of the build. I am not clear on what the solution there is - ignore it? Add the type and re-export them? Just exploring this now,

**Comment by josephjclark** [comment]
Huh, ok, so the first issue isn't actually axios - it's `export { del as delete }` that's killing the DTS compilation.

It's the `delete` keyword, rather than the `export as`, that's causing the problem.

**Comment by taylordowns2000** [comment]
🤦 Whoa. Amazing find. Personally, I'd be happy to introduce a breaking change to `common.http` in this case... _if_ you feel like we shouldn't have a function called delete.

I doubt that many other adaptors use it anyway, and they'd be easy to update via the monorepo.

Thoughts?

**Comment by josephjclark** [comment]
Progress update.  The error comes put of rollup, so you'd think this is a rollup problem. This sort of thing has been raised as a bug in the past but appears to be fixed now.

If I run `rollup-plugin-dts` standalone with 4.2.1, it's quite happy to build `common/http` with `export { del as delete }`. No problem.

But running the same plugin (same version) through `tsup` throws the error.

Weird and getting weirder.

**Comment by josephjclark** [comment]
Wait wait wait I think I have it. If I set `allowJS` to `false` in compiler options, it seems to work.

**Pull request merged**
