### PR TITLE
`primero` remove examples from developer readme

### PR DESCRIPTION
**Pull request by aleksa-krolls**
examples should be in the inline adaptor documentation, not in the dev readme.

@mtuchi , can you discuss this with @taylordowns2000 and make sure that all examples and comments removed here are included in the inline adaptor documentation?

### CODE REVIEW

**Comment by mtuchi** [comment]
@aleksa-krolls we have an issue that will fix the `jsdoc` #165 , this will include moving examples from readme to doc string 
I will chat with @taylordowns2000 on how we can prioritize this because there is a lot to be covered

**Comment by mtuchi** [comment]
@taylordowns2000, I have added all examples to adaptors docstring now, you can review now

**Review by taylordowns2000 — DISMISSED** [review]
@mtuchi , can you please:
1. Run a linter with our standard prettier settings on these examples. They look improperly spaced and line broken for readability 
2. Confirm that the new arguments are working with the primero v2 api? Are these actual working examples, and if so how did you verify them?

For number 2, this is a question we will keep coming back to over and over as we update the docs for various adaptors, so it's worth thinking through well.

**Comment by mtuchi** [comment]
> @mtuchi , can you please:
> 
> 1. Run a linter with our standard prettier settings on these examples. They look improperly spaced and line broken for readability
> 2. Confirm that the new arguments are working with the primero v2 api? Are these actual working examples, and if so how did you verify them?
> 
> For number 2, this is a question we will keep coming back to over and over as we update the docs for various adaptors, so it's worth thinking through well.

I have update the examples that i could find from different primero repo @taylordowns2000

**Review by taylordowns2000 — APPROVED** [review]

**Pull request merged**
