### PR TITLE
`hive` update `hive-driver` package

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Update `hive-driver ` package to `1.0.0`

Fixes

- https://github.com/OpenFn/adaptors/security/dependabot/96

## Details
- Recursively update `ws`, `pnpm update ws -r`
- Then `pnpm i && pnpm build`
- Then `pnpm test`

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### CODE REVIEW

**Comment by josephjclark** [comment]
Hmm. I was a bit surprised to even see a dependency on `ws`, because it's a web socket server library and we don't have any interest in creating a websocket server.

Digging in, it looks like this comes from `hive-driver@0.2.0`. I think you can update hive-driver to `1.0.0` (there are no breaking changes listed in the [changelog](https://github.com/lenchv/hive-driver/blob/9a80e888408cd32e197edfa567d1c4625c86c121/CHANGELOG.md)) and everyone will be happy.

Because we don't run any websocket servers I'm happy to dismiss the alert. It doesn't affect us. But a bump on `hive-driver` would be nice as it should clear out any alerts/vulnerabilities/warnings associated with it.

Also: there is no AI disclosure in this PR - please add one ( you can just add a line saying "I did not use AI in this PR", if you like).

**Comment by mtuchi** [comment]
@josephjclark I have updated the `hive-driver` and the PR description . I don't have unit tests though for `hive` adaptor 😞

**Comment by josephjclark** [comment]
@mtuchi are you able to run a manual test from back when you wrote the adaptor?

I am very confident that the upgrade is safe, but if you have a credential and can re-run a basic job, that would take me from 90% to 99% confidence. Worth it if you can do it in 10 minutes. If not I'll merge.

**Comment by mtuchi** [comment]
@josephjclark unfortunately i don't have any way of testing this. It require an apache hive database which i no longer have in my pc.

**Comment by josephjclark** [comment]
@mtuchi Ok that's cool - thanks for clarifying.

Like I say, I'm very confident in the update (no breaking changes listed). So let's just punch it in

**Pull request merged**
