### PR TITLE
`msgraph` adaptor

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Add a `get()` and `create()` function

## Review Checklist

Before merging, the reviewer should check the following items:

- [x] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, has the migration tool been run and the
      migration guide followed?
- [ ] Are there any unit tests? Should there be?
- [x] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
hey @mtuchi , this looks good. two things before merging:
1. i think the icons didn't get added
2. would you please help me merge #280 and _then_ rebase this on main? want to make sure it's not susceptible to the reassignment issues we've detected with `each`

**Comment by mtuchi** [comment]
@taylordowns2000 i have updated the read me with  Microsoft logo

**Comment by mtuchi** [comment]
@taylordowns2000 i have rebased and pushed the `sharepoint` suggestions, This is ready for review now

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@mtuchi , this is super close. it looks to me like the changelog and changesets are not quite right. as this is the first release of msgraph, i'd expect the version to be `0.1.0`. can you get this cleaned up then I'll merge and you can release to npm?

**Pull request merged**
