### PR TITLE
`mssql` update port configuration-schema

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Add `title` and `description` for port configuration 

Ref #630 

## Review Checklist

- [x] Does the PR do what it claims to do?
- [ ] Are there any unit tests? Should there be?
- [x] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

### CODE REVIEW

**Review by josephjclark — APPROVED** [review]
This is cool but what broke?

If Lightning is failing because the schema lacks a name and description, that needs raising as a bug in Lightning.

**Comment by josephjclark** [comment]
Also something is wrong with pnpm.

I think it's temporary, and as there's no code changes here I'm happy to merge with CI failing

**Comment by mtuchi** [comment]
The mssql credential form on lightning was missing a title so when creating a new credential the form input title is empty 
Screenshot 2024-07-05 at 9 08 20 AM

**Comment by mtuchi** [comment]
> @mtuchi is there an issue to cover that on the Lightning side? It should be more robust

@josephjclark i opened up an issue yesterday on lightning but it does not mention the port title issue which will be resolved by this PR, See the issue here https://github.com/OpenFn/lightning/issues/2255

**Comment by josephjclark** [comment]
That's a different issue though.

The issue here is that if a field does not have a title, it'll be totally blank in the UI. You can use port as an example but it affects all future schema

**Comment by mtuchi** [comment]
> That's a different issue though.
> The issue here is that if a field does not have a title, it'll be totally blank in the UI. You can use port as an example but it affects all future schema

Okay i will bring it up in a stand up, I am not sure how lightning is suppose to solve this  but i have created an issue here https://github.com/OpenFn/lightning/issues/2259.

**Comment by josephjclark** [comment]
Thank you. It's not your job to solve the issue. You just have to report it!

**Review by josephjclark — APPROVED** [review]

**Comment by josephjclark** [comment]
@mtuchi please run `pnpm changeset version` , commit the diffs, run `pnpm changeset tag`, and push the new commits and tags

**Comment by mtuchi** [comment]
Done i have pushed the new tag

**Pull request merged**
