### PR TITLE
`openmrs` update upsert operation

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Remove `prepareNextState` on the upsert operation  since it will be handled in `update` or `create` operation. I have also added 

## Review Checklist

- [x] Does the PR do what it claims to do?
- [x] Are there any unit tests? Should there be?
- [x] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.

### CODE REVIEW

**Comment by josephjclark** [comment]
Hi @mtuchi, is this ready for review?

Can you please update the PR description and text to indicate what has changed in upsert?

You'll want a changeset too

**Comment by mtuchi** [comment]
@josephjclark this is ready for review

**Comment by josephjclark** [comment]
@mtuchi Can you update the PR title and description please to explain what you've done?

Generic PRs like "update upsert" aren't helpful when a) reviewing a PR or b) looking back over history to understand what's changed. This githib admin is actually support important

**Comment by mtuchi** [comment]
@josephjclark i have updated the PR description, I want to cut a release for this adaptor It's needed on msf workflow latest changes

**Review by josephjclark — APPROVED** [review]

**Pull request merged**
