### PR TITLE
dhis2: fix integration tests

### LINKED ISSUE #207: DHIS2 integration tests are broken
* `cd adaptrs/dhis2`
* `pnpm integration-tests`

Tests fail for a wild variety of reasons.

Part of it is an ESM thing (which I expect to get fixed with the magic functions work), but it looks like even when you get the tests running, they go on to fail.

### PR DESCRIPTION
**Pull request by josephjclark**
## Summary

Two fixes for DHIS2:

* Fix an issue resolving the `path` argument to `update`
* Restore Integration tests

Fixes #207

## Details

Integration tests should now run locally (but never in CI)

The state of the sandbox may cause failures in future, but they're working at the moment

Thanks to @mtuchi  for help

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### CODE REVIEW

**Comment by josephjclark** [comment]
@mtuchi can you give this a look over, maybe run it locally `pnpm test:integration` from within the adaptor folder

**Comment by mtuchi** [comment]
There are couple of unit test that are failing, I will investigate more on Monday

**Comment by josephjclark** [comment]
@mtuchi You mean integration tests? If they're failing because of data being a bit different then I'm not too worried. So long the API feels like it's working and returning good errors, I'm happy enough. Let's see on Monday

**Review by mtuchi — APPROVED** [review]
Hiya @josephjclark i have looked at the integration tests everything looks good. 
The test that are failing are okay because it's related to the data. 

I have pushed a tiny change to increase a timeout out in one of the test and remove fields query which takes time to return the response

I think on @hunterachieng PR there are couple of changes that will have to happen in integration tests so far now this good enough 👍🏽

**Pull request merged**
