### PR TITLE
Update `mocha` to `10.7.3`

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Update `mocha` package to `10.7.3`

## Details
- Recursively update `mocha@10.7.3`, `pnpm update mocha@10.7.3 -r`
- Then `pnpm i && pnpm build`
- Then `pnpm test`
- Add changeset and commit changes

Fixes #
- #746 

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Review Checklist

- [x] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, added the adaptor on marketing website ?
- [ ] Are there any unit tests?
- [x] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.
- [x] Have you ticked a box under AI Usage?

### CODE REVIEW

**Comment by josephjclark** [comment]
@mtuchi Thank you for this! A few things here:

1. Please update your AI disclosure (I see you've done it elsewhere, thank you!)
2. Unfortunately, because `mocha` is a dev dependency and doesn't ship with the adaptor, we don't need a changeset or release here. We just need to bump the internal version dependencies and no more.

**Comment by mtuchi** [comment]
@josephjclark i have update the AI usage and remove the changeset. I am curious what do you mean bump internal version dependencies ?

**Comment by josephjclark** [comment]
What I mean is we don't need to cut any releases here. This change does not affect adaptors at all in the CLI or Lightning.

We just need to update the `devDependencies` on `mocha`, and merge that into main.

Stretch goal: you should actually be able to remove `mocha` from each individual package (`pnpm -r remove mocha`), and then re-add it as a devDepedency at root (I think `pnpm add -Dw mocha` - where -w allows a package to be added to the workspace root). That will be a little bit cleaner :)  Packages in the monorepo will still be able to see the root dependencies, so tests will still run.

**Comment by mtuchi** [comment]
@josephjclark i have remove `mocha` from all packages and re-add as devDependency at root. I also confirm `pnpm test` still works as expected

**Comment by josephjclark** [comment]
Awesome @mtuchi, this looks a lot cleaner. Thank you!

**Pull request merged**
