### PR TITLE
update axios to latest version

### PR DESCRIPTION
**Pull request by mtuchi**
## Summary

Update axios version to `1.7.7` for 
```
dhis2
godata
mailchimp
openfn
progres
rapidpro
salesforce
```

Fixes #
- https://github.com/OpenFn/adaptors/issues/727

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Review Checklist

Before merging, the reviewer should check the following items:

- [x] Does the PR do what it claims to do?
- [ ] If this is a new adaptor, added the adaptor on marketing website ?
- [ ] Are there any unit tests?
- [x] Is there a changeset associated with this PR? Should there be? Note that
      dev only changes don't need a changeset.
- [x] Have you ticked a box under AI Usage?

### CODE REVIEW

**Comment by mtuchi** [comment]
Unit test are passing but i am not sure if that is enough because some of the adaptors do not have unit test 🤔

**Comment by josephjclark** [comment]
Hi @aleksa-krolls, @christad92:

There is a very low risk of some of these adaptors breaking as a result of this PR. If any of these were to break, would anyone be upset?
```
godata
openfn
progres
rapidpro
```

**Comment by josephjclark** [comment]
@mtuchi Nice, I'm glad that dhis2 looks good.

I think so long as dhis2, salesforce and mailchimp are OK, this is worth the risk and I'm happy to merge. Even if we do break something it should be easy for users to to roll back a patch. But I'm just checking in with the adults first.

PS: Please update the AI disclosure :pray:

**Comment by mtuchi** [comment]
@josephjclark i have updated the AI usage and fixed the merge conflict

**Review by josephjclark — APPROVED** [review]
@mtuchi when the build is restored this will need rebasing and bumping.

Please bump the versions and re-assign me to release. Thanks!

**Comment by mtuchi** [comment]
Hiya @josephjclark i have bump version and push the changes. But i am noticing modification in this file `packages/fhir-ndr-et/src/builders.js`. Is this expected ? I haven't pushed the tags yet, let me know if i should do so

**Comment by josephjclark** [comment]
@mtuchi Are you sure you used the very latest main? #777 was merged very recently and it should have the same diff. I suspect GH is lying but please double check your main

We've got a bit of a problem in `fhir-ndr-et`  #776  which I'll fix next week, which will cause this sort of thing to happen :(

**Comment by mtuchi** [comment]
@josephjclark  My latest commit on main is ffa10a80e after git pull, when i run `pnpm i && pnpm build` it  modified:   `packages/fhir-ndr-et/src/builders.js`

**Comment by josephjclark** [comment]
@mtuchi OK I've updated main. Can you please revert the changes to `fhir-ndr-et` and merge main? 

This should get rid of these strange diffs.

**Comment by josephjclark** [comment]
Thank you @mtuchi ! Remember that tags are automated now. No need to push manually.

**Comment by mtuchi** [comment]
Ooh thank you kindly for the reminder, that is really good news 😃

**Pull request merged**
